"""This file contains application constants like maximum lengths"""

DEFAULT_RECORDS_PER_PAGE = 10
MAX_RECORDS_PER_PAGE = 100

GENERAL_NAME_MIN_LENGTH = 2
GENERAL_NAME_MAX_LENGTH = 128
GENERAL_DESCRIPTION_MIN_LENGTH = 2
GENERAL_DESCRIPTION_MAX_LENGTH = 255
EMAIL_MAX_LENGTH = 256
TAX_ID_MAX_LENGTH = 16
PASSWORD_MIN_LENGTH = 6
ANALYSIS_DESCRIPTION_MAX_LENGTH = 1024
