"""This file contains application constants like maximum lengths"""

DEFAULT_RECORDS_PER_PAGE = 10
MAX_RECORDS_PER_PAGE = 100

GENERAL_NAME_MAX_LENGTH = 128
GENERAL_DESCRIPTION_MAX_LENGTH = 255
EMAIL_MAX_LENGTH = 256
TAX_ID_MAX_LENGTH = 16
